before:
  hooks:
    - go mod tidy
builds:
  - id: cli
    main: ./yomo/main.go
    binary: yomo
    ldflags:
      - -w -s
      - -X github.com/bytebase/bytebase/bin/bb/cmd.version={{.Version}}
      - -X github.com/bytebase/bytebase/bin/bb/cmd.goversion=${GO_VERSION}
    tags:
      - release
    env:
      - VERSION="development"
      - GO_VERSION="1.19"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
snapshot:
  name_template: "{{ incpatch .Version }}-next"